baseURL = 'https://wallabra.github.io/livrezine'
languageCode = 'pt-br'
title = 'LivreZine'
theme = "spaced-blog"
description = "A publicação urbanista mais antenada da Zona Norte de Porto Alegre!"

[params]
useCover = true

[[params.author]]
name = "Gustavo Ramos Rehermann"

[security.exec]
allow = ["asciidoctor"]
