---
title: "1ª Edição"
date: 2024-02-29T12:15:07-03:00
draft: false
---

= 1ª Edição

A primeira edição do LivreZine foi escrita e impressa no dia 28 de fevereiro de
2024. Consigo traz dois temas: os *custos sociais insustentáveis da
infraestrutura rodoviária*, onde denuncia a epidemia de estacionamentos e
viadutos e demais infraestrutura, que desperdiça verba pública e degrada os
ambientes urbanos; e a *Omafiets*, a bicicleta de rua padrão da Holanda, na
qual homens e mulheres trafegam para trabalhar e passear todos os dias.

Seguem os artigos.

== Infraestrutura rodoviária: Cara, estéril, ineficiente, e distante

Um dilema tão século XX quanto a bomba atômica, tão pervsaivo quanto o futebol,
e tão tangível quanto a calçada sob as solas dos pés. Os espaços urbanos de hoje
são tomados por ruas desenhadas para os carros e SUVs, com pouco espaço para
ciclismo ou transporte público.

Todos os anos, desperdiçam-se milhões de reais  na construção e manutenção de
infraestrutura pública cujo único propósito é servir o conforto e a
conveniência de motoristas. Desde viadutos e avenidas alargadas, a
estacionamentos públicos e em beiradas, tudo isso configura um subsídio aos
motoristas, pago por toda a sociedade, com pouco Retorno sobre Investimento.
Pelo menos nossa cidade não chega ao nível que subúrbios americanos enfrentam
deste problema.

Existem, sim, modos mais sustentáveis de projetar o transporte e os espaços
urbanos onde vivemos. Começando pelas próprias vias, onde o espaço trafegável
por carro deve estreitar, abrindo mais espaço para pessoas, sejam pedestres ou
ciclistas; e mais e melhor transporte público, que merece mais opções
diversificadas; e menos espaço reservado para estacionamento, incentivando o
uso de meios alternativos de transporte.

Menos espaço devotado aos carros e a estacionamento significa mais espaço para
prédios residenciais e estabelecimentos comerciais, e mais espaço para
transporte público, por sua vez incentivando desenvolvimentos urbanos de
densidade média, que maximizam a receita pública sobre a mesma área. Assim, é
financeiramente sustentável  ter prédios próximos e aglomerados, acessíveis e
que movimentam a economia e pagam impostos, ao invés de enormes viadutos cuja
crua capacidade apenas se justifica nos horários de pico, em duas das 24 horas
de um dia.

== Conheça a omafiets: Os segredos da bicicleta neerlandesa

Não é segredo para ninguém que, quando o assunto é bicicleta e urbanismo,
poucos chegam perto à proeza dos holandeses. Isso reflete também no design mais
comum de bicicleta por lá, a Omafiets, que uma enorme parcela da população usa
para ir ao trabalho, às compras, ou mesmo passear para lazer, todos os dias.

Esse engenhoso design combina ergonomia, com uma barra transversal abaixada,
que facilita o ciclista na hora de subir e descer da bicicleta, e durabilidade,
sendo feita de aço ao invés de alumínio ou fibra de carbono, sendo assim
otimizado para uso regular ao invés de leveza e performance esportiva.

Também conta com vários acessórios embutidos, como pára-lamas sobre as rodas,
uma grade atrás do banco (para, por exemplo, apoiar as compras), e dispositivos
de segurança essenciais como o farol e a buzina, comumente ligados a um dínamo
ao invés de uma bateria.

Mas não basta uma bicicleta utilitária sem a infraestrutura e os espaços urbanos
propícios para a sua adoção e uso como parte do dia-a-dia dos cidadãos.
Precisamos de mudanças profundas na cidade se queremos atingir o alto padrão
neerlandês, onde a bicicleta é não apenas de todos, mas de todo dia.
