---
title: "2ª Edição"
date: 2024-04-04T11:52:29-03:00
draft: false
---

= 2ª Edição

A segunda edição do LivreZine foi escrita e impressa no dia 19 de março de
2024. Consigo traz dois temas: o *aumento na popularidade dos SUVs* e as
consequências desastrosas destes para a vida urbana; e um argumento em
prol de *veículos sobre trilhos como forma ótima de transporte público*.

Seguem os artigos.


== Epidemia dos SUVs: Impraticalidade, espaço ocupado, poluição, e perigo no
trânsito!

SUVs carecem de economia de combustível, versatilidade, manobrabilidade, e
visibilidade. O capô alto atrapalha a visão do motorista e pode ocultar
pedestres e obstáculos baixos na frente do veículo. Também tem menos espaço
útil para bagagem do que uma minivan.

Dadas estas informações, você pode estar se perguntando: porque alguém iria
querer usar um veículo ineficiente, pesado, perigoso, caro, e impraticável?

A realidade sempre é mais complexa. Nos Estados Unidos, a indústria
automobilística vem, há anos, fazendo lobbying pesado contra regulações de
economia de combustível e de emissões poluentes (CAFE, na sigla inglesa –
Corporate Average Fuel Economy). Na prática, a indústria conseguiu abrir uma
exceção para SUVs, ao classificá-los como light trucks (caminhões leves) ao
invés de carros. Assim, conseguem regulações mais branda, e um lucro mais
facilitado.

Isso, juntamente com marketing pesado, tornou propícia a disseminação massiva
do SUV como meio de transporte primário hoje em dia, substituindo sedãs e
carros mais compactos.

As consequências são bem visíveis: vagas de estacionamento maiores, exigindo
ainda mais espaço de estacionamento para (des)ocupar grandes fatias de
loteamento urbano; mais espaço ocupado no trânsito, agravando
congestionamentos; mais perigo na estrada para pedestres, ciclistas, e até
motoristas em carros compactos; menos economia de combustível média,
significando mais consumo de combustíveis fósseis; e segue a lista.


== Trilhos: o antídoto contra viadutos largos e caros

Em um mundo dominado por automóveis, viadutos se tornam as artérias que ligam
bairros e cidades distantes. Quem nunca passou uma semana de verão numa cidade
praiana?

Claro, chegar lá a carro, em um viaduto, é bem pior. Se não bastassem as vistas
monótonas de uma canaleta gigante de concreto, por algum motivo, todo mundo
quer usar o mesmo viaduto, ao mesmo tempo, causando um engarrafamento! Ah, se
houvesse um jeito de mover toda essa gente junto, com celeridade! Pior, viadutos
desperdiçam muito dinheiro público com a manutenção de todo esse concreto.

Felizmente, trens se distinguem nesse sentido: comportam muitas pessoas,
conectam várias cidades e bairros ao longo de uma rota, e podem alcançar altas
velocidades. E como já são guiados por trilhos, dá para curtir a vista de
dentro do trem, ou se entreter ou antecipar trabalho em seu laptop, ao invés de
dirigir..

Claro, para que seja um meio de transporte competitivo que convença as pessoas
a largarem seus volantes, precisa de rotas bem planejadas, vagões confortáveis
e mantidos, e acess conveniente, bem integrado a outros meios de transporte,
como bicicletas e ônibus. E isso exige investimento social e de políticas
públicas que incentivam o transporte público.
