---
title: "3ª Edição"
date: 2024-08-27T12:17:11-03:00
draft: false
---

= 3ª Edição

A terceira edição do LivreZine foi escrita e impressa no dia 27 de agosto de
2024, quebrando um hiato de vários meses.

Consigo traz dois temas: os *ecos da enchente*, onde reflete sobre as
consequências da enchente para a cidade, inclusive as mais sutis; e os
*Superblocos*, uma nova moda do planejamento de matrizes urbanas, pioneirada
em Barcelona, na Espanha, que leva a pedestrianização dos bairros a um novo
patamar.

Seguem os artigos.

== Ecos da Enchente: O desafio de revitalizar as ruas e _reacender_ a vida urbana

Sem enrolação: fomos vítimas de um severo desastre climático, que no Rio Grande
do Sul resultou no falecimento de 172 pessoas e desalojou 629 mil – mais de
meio milhão!  As estatísticas estão por tudo que é lado, e por mais que, a essa
altura do jogo, já estejamos lentamente recuperando o ritmo da vida cotidiana,
é impossível desviar completamente dos ecos da enchente que ainda assolam nossa
cidade. Muito já foi falado dessa catástrofe geral, mas vamos abordar a
perspectiva urbanista, àquilo que abrange a vida nas ruas e nos bairros de
Porto Alegre.

A ação da correnteza encheu a rua com 30 toneladas de entulhos, exigindo um
esforço de limpeza que ainda perdura e ainda perdurará possivelmente por meses.
E, para construir o corredor humanitário emergencial, foi necessária a
demolição da passarela pedestre da Rodoviária. A sua reconstrução também será
um empreendimento considerável.

As águas também afetaram a operação das estações de trem, que até a publicação
desta edição ainda estão em processo de reabilitação entre a estação Mercado
e Farrapos. A previsão é que haja reabertura da estação Farrapos até o dia
20 de setembro, e até a estação Mercado até a véspera de Natal.

Quanto às ruas em si, nos bairros afetados, ainda seguem visíveis as marcas da
enchente: a marca d’água segue visível em vários prédios, e as árvores e os
canteiros seguem mortos, afogados de água, lama, lodo e sujeira. Essa diferença
é notável para qualquer um que conhecia o estado anterior das ruas. Detalhes
como estes configuram os ecos da enchente, as consequências mais sutis, e
também perenes, deste cataclísmico evento. Mesmo quando as ruas forem limpas e
os trens continuarem a trafegar, sempre haverá uma árvore desfolhada para nos
lembrar do mês em que nosso espírito se afogou.


== Pedestrianização & Superblocos: a revolução urbanista de Barcelona

Barcelona já passou por um cenário revolucionário no passado, durante a grande
Guerra Civil Espanhola. Hoje, um tipo bem diferente de revolução surge em seu
berço pioneiro: os superblocos.

São uma forma nova de planejar espaços urbanos, que secionam a malha urbana de
tal modo que as quadras, maiores, e bordadas por prédios de densidade, abrigam
adentro espaços pedestres, com bares, lojas, academias, e todo tipo de vida
urbana. Como na imagem acima, onde os prédios grandes, geralmente residenciais,
anelam os espaços interiores, adentráveis por vielas e repletos de vida.

Adotar uma matriz assim em uma cidade antiga como Porto Alegre pode ser um
desafio, já que demolir bairros já existentes está fora de questão, mas o
superbloco demonstra a viabilidade de um conceito que pode ser aplicado para a
construção de novos bairros.

Afinal, nada melhor para a revitalização dos bairros após o desastre da
enchente, do que morar numa quadra do lado de uma praça e uma lanchonete, num
passeio sem o barulho de carros adjacentes, relaxando num banco e tomando um
belo chimarrão. 🖤
